version: "1.0"

services:
  backend:
    build: .
    container_name: bank-rest-api
    ports:
      - "8090:8090"
    environment:
      BC_DATABASE_HOST: db
      BC_ADMIN_PASSWORD: ${BC_ADMIN_PASSWORD:-12345}  # If the environment variable is not set, default password will be used
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: bcms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: