server:
  port: 8090

app:
  jwt:
    lifetime: PT30M # 30 minutes
    secret: ${BC_JWT_SECRET:lkjdf-pe9KJ0hkm1fls-L7K-la4IWlajPO0WE}

  admin:
    email: admin@gmail.com

  card:
    encryption:
      secret: ${BC_CARD_ENCRYPTION_SECRET:lelasd-aldiwmfif}

  origin: ${BC_ORIGIN:*}

logging:
  level:
    root: INFO
    com.example.bankcards: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG		

spring:
  application:
    name: bank-rest-api
  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml        
  datasource:
    url: jdbc:postgresql://${BC_DATABASE_HOST:localhost}:${BC_DATABASE_PORT:5432}/${BC_DATABASE_NAME:bcms}
    username: ${BC_DATABASE_USERNAME:postgres}
    password: ${BC_DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    url: /openapi.yaml