server:
  port: 8090

jwt:
  lifetime: T30M // 30 minutes
  secret: ${BC_JWT_SECRET:lkjdf-pe9KJ0hkm1fls-L7K-la4IWlajPO0WE}

spring:
  application:
    name: bank-rest-api
  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml        
  datasource:
    url: jdbc:postgresql://${BC_DATABASE_HOST:localhost}:${BC_DATABASE_PORT:5000}/${BC_DATABASE_NAME:bcms}
    username: ${BC_DATABASE_USERNAME:postgres}
    password: ${BC_DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always